### ISSUE TITLE
URL should be under *.midburn.org

### ISSUE THREAD

**Issue by ripper234** [Midburn/camps_index#1]
Currently the theme camps pages are on Heroku:

http://midburn-themecamps.herokuapp.com/published-camps-he
http://midburn-themecamps.herokuapp.com/published-camps

We should configure Heroku to have the websites at something like:

http://camps.midburn.org/published-camps-he
http://camps.midburn.org/published-camps

**Comment by mtr574** [comment]
Irrelevant.
