### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mtr574** [Midburn/camps_index#3]
List of issues:

1. הסידור לפי א״ב לא עובד טוב. לא ברור לפי מה הוא מסדר את המחנות.
2. עדכון מחנות חדשים + דברים שהשתנו - כמו שאמרתי, אתה יכול לתת לנו גישה ונעשה את זה לבד. אביב יהיה בקשר איתך שתסביר לו בדיוק איך לעשות את זה.
3. On hover על התפריט בצד ימין לא עובד כמו בשאר העמודים (jQuery implementation)
4. מחנה חצילים מופיע פעמיים

**Comment by natekonimbo** [comment]
fixed.
