### ISSUE TITLE
[question] where do we get final 2018 open camps data? 

### ISSUE THREAD

**Issue by OriHoch** [Midburn/camps_index#8]
it's public data so you can upload it to this issue... or send me privately, as you wish

alternatively- if spark data is updated I can take it from spark

**Comment by eavitan** [comment]
Hey @OriHoch ,

According to Panda, the data needs to be from the Spark, if the current URL is not it, please send me the updated link, else, allow access.

thanks :)

**Comment by pandamichal** [comment]
The theme camps data comes from Spark,Teme camp managers updating their contact details and if they are open to new people.  This should be updated automatically and presented as DATA  on the website.I hope it's more clear right now. @alex_motenko

**Comment by OriHoch** [comment]
:+1:

**Comment by pandamichal** [comment]
Hey guys! The feature is not working.. more details here: https://github.com/Midburn/spark/issues/696

**Comment by OriHoch** [comment]
it's not working because it wasn't implemented yet

**Comment by OriHoch** [comment]
done in [camps index v1.3.0](https://github.com/Midburn/camps_index/releases/tag/v1.3.0), automatically updated from spark every 10 minutes, continuously deployed to https://production.midburn.org/camps-2018/

**Comment by pandamichal** [comment]
cool- another thing that needs to be added: "show link to facebook page" - only if the camp updating the link it should be shown on the website with the other details.

**Comment by OriHoch** [comment]
@pandamichal please open a new issue.. this issue is closed
